# Generated by Django 3.1 on 2020-11-25 12:40

import django.core.validators
from django.db import migrations, models
import taxi.backends.storage_backends
import taxi.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20201113_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=taxi.backends.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UploadPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=taxi.backends.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', taxi.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: (+216)xxxxxxxx', regex='^\\+216\\d{8}$')]),
        ),
    ]
