# Generated by Django 3.1 on 2020-11-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_user_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
