# Generated by Django 3.1 on 2020-11-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
